{% set name = "django-pkgconf" %}
{% set version = "0.3.0" %}
{% set sha256 = "822bd778238828920d6f3b458a185e8b85d1eac689dddb1e2e38ec44234359ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/byashimov/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django

test:
  requires:
    - python {{ python_min }}
  imports:
    - pkgconf

about:
  home: https://github.com/byashimov/django-pkgconf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Yet another application settings helper'
  description: 
    Yet another application settings helper
  doc_url: https://github.com/byashimov/django-pkgconf
  dev_url: https://github.com/byashimov/django-pkgconf

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
